import { 
  Organization, 
  Branch, 
  User, 
  Course, 
  Subject, 
  Batch, 
  Student, 
  Lead, 
  ClassSession, 
  AttendanceRecord, 
  FeePlan, 
  Invoice, 
  Payment, 
  Question, 
  Test, 
  Intervention, 
  AuditLog 
} from '../types';

export const SEED_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-kota-001',
    legalName: 'Aarohan Educational Foundation Pvt Ltd',
    tradeName: 'Aarohan JEE Academy',
    gstin: '08AAACA1234F1Z5',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    tier: 'PRO_INSTITUTE',
    status: 'ACTIVE',
  },
  {
    id: 'org-pune-002',
    legalName: 'Apex Career Institute LLP',
    tradeName: 'Apex CAT & Banking Prep',
    gstin: '27AABCA5678K1Z3',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    tier: 'GROWTH',
    status: 'ACTIVE',
  },
  {
    id: 'org-blr-003',
    legalName: 'Pragati Learning Systems',
    tradeName: 'Pragati Tuition Centre',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    tier: 'STARTER',
    status: 'ACTIVE',
  },
  {
    id: 'org-hyd-004',
    legalName: 'Drona Skilltech Solutions Pvt Ltd',
    tradeName: 'Drona Tech Academy',
    gstin: '36AABCD9012J1Z8',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    tier: 'GROWTH',
    status: 'ACTIVE',
  },
  {
    id: 'org-del-005',
    legalName: 'Sankalp Vidyamandir Educational Society',
    tradeName: 'Sankalp Academy Delhi',
    gstin: '07AAATS4321D1Z1',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    tier: 'MULTI_BRANCH',
    status: 'ACTIVE',
  },
];

export const SEED_BRANCHES: Branch[] = [
  {
    id: 'br-kota-main',
    organizationId: 'org-kota-001',
    branchCode: 'KOTA_TLW',
    name: 'Talwandi Centre',
    address: 'Plot 42, Sector A, Talwandi',
    city: 'Kota',
    state: 'Rajasthan',
    pincode: '324005',
    phone: '+917442401101',
    status: 'ACTIVE',
  },
  {
    id: 'br-kota-vigyan',
    organizationId: 'org-kota-001',
    branchCode: 'KOTA_VHR',
    name: 'Vigyan Nagar Campus',
    address: 'Road No. 2, Vigyan Nagar',
    city: 'Kota',
    state: 'Rajasthan',
    pincode: '324007',
    phone: '+917442401102',
    status: 'ACTIVE',
  },
  {
    id: 'br-pune-fc',
    organizationId: 'org-pune-002',
    branchCode: 'PUNE_FC',
    name: 'FC Road Centre',
    address: '3rd Floor, Prestige Point, FC Road',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411004',
    phone: '+912025531201',
    status: 'ACTIVE',
  },
  {
    id: 'br-blr-jyn',
    organizationId: 'org-blr-003',
    branchCode: 'BLR_JYN',
    name: 'Jayanagar 4th Block',
    address: '14, 11th Main, Jayanagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560011',
    phone: '+918026639900',
    status: 'ACTIVE',
  },
  {
    id: 'br-hyd-mad',
    organizationId: 'org-hyd-004',
    branchCode: 'HYD_MAD',
    name: 'Madhapur Tech Hub',
    address: 'Cyber Towers Lane, Madhapur',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    phone: '+914023114455',
    status: 'ACTIVE',
  },
  {
    id: 'br-del-jan',
    organizationId: 'org-del-005',
    branchCode: 'DEL_JAN',
    name: 'Janakpuri West Campus',
    address: 'B-1/14, Janakpuri',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110058',
    phone: '+911125501122',
    status: 'ACTIVE',
  },
];

export const SEED_USERS: User[] = [
  // Aarohan Kota Users
  {
    id: 'usr-rajesh-owner',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919829012345',
    email: 'rajesh.sharma@aarohan.edu.in',
    fullName: 'Dr. Rajesh Sharma',
    role: 'OWNER',
    designation: 'Managing Director & Founder',
  },
  {
    id: 'usr-alok-teacher',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919829023456',
    email: 'alok.mukherjee@aarohan.edu.in',
    fullName: 'Prof. Alok Mukherjee',
    role: 'TEACHER',
    designation: 'Head of Physics Faculty',
  },
  {
    id: 'usr-pooja-counsellor',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919829056789',
    email: 'pooja.verma@aarohan.edu.in',
    fullName: 'Pooja Verma',
    role: 'COUNSELLOR',
    designation: 'Senior Admission Counsellor',
  },
  {
    id: 'usr-suresh-accountant',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919829045678',
    email: 'suresh.nair@aarohan.edu.in',
    fullName: 'Suresh Nair',
    role: 'ACCOUNTANT',
    designation: 'Senior Fee Accountant',
  },
  {
    id: 'usr-ishita-student',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919414011111',
    email: 'ishita.mehra@student.aarohan.edu.in',
    fullName: 'Ishita Mehra',
    role: 'STUDENT',
    designation: 'JEE 2027 Aspirant',
  },
  {
    id: 'usr-mehra-parent',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    phone: '+919810123400',
    email: 'vikram.mehra@example.com',
    fullName: 'Vikram Mehra (Parent)',
    role: 'PARENT',
    designation: 'Father & Guardian of Ishita',
  },
];

export const SEED_COURSES: Course[] = [
  {
    id: 'crs-jee-adv',
    organizationId: 'org-kota-001',
    name: '2-Year Integrated JEE Advanced 2027',
    targetExam: 'JEE_ADVANCED',
    durationMonths: 24,
    status: 'ACTIVE',
  },
  {
    id: 'crs-neet-med',
    organizationId: 'org-kota-001',
    name: 'NEET Excellence 1-Year Dropper Batch',
    targetExam: 'NEET_UG',
    durationMonths: 12,
    status: 'ACTIVE',
  },
  {
    id: 'crs-cat-comp',
    organizationId: 'org-pune-002',
    name: 'CAT 2026 Comprehensive Masterclass',
    targetExam: 'CAT',
    durationMonths: 9,
    status: 'ACTIVE',
  },
  {
    id: 'crs-cbse-10',
    organizationId: 'org-blr-003',
    name: 'Class 10 CBSE Math & Science Sprint',
    targetExam: 'CBSE_10',
    durationMonths: 10,
    status: 'ACTIVE',
  },
];

export const SEED_BATCHES: Batch[] = [
  {
    id: 'bat-jee-2027-evening',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    courseId: 'crs-jee-adv',
    name: 'JEE Main 2027 Evening (Super 40)',
    academicYear: '2025-2027',
    maxCapacity: 40,
    currentEnrollment: 36,
    startDate: '2025-06-01',
    endDate: '2027-05-30',
    status: 'ACTIVE',
  },
  {
    id: 'bat-jee-2027-morning',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    courseId: 'crs-jee-adv',
    name: 'JEE Main 2027 Morning Regular',
    academicYear: '2025-2027',
    maxCapacity: 60,
    currentEnrollment: 54,
    startDate: '2025-06-01',
    endDate: '2027-05-30',
    status: 'ACTIVE',
  },
];

export const SEED_STUDENTS: Student[] = [
  {
    id: 'stu-000184',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    studentUniqueId: 'STU-KOTA-2026-001',
    fullName: 'Ishita Mehra',
    gender: 'FEMALE',
    dob: '2009-04-14',
    phone: '+919414011111',
    email: 'ishita.mehra@student.aarohan.edu.in',
    batchId: 'bat-jee-2027-evening',
    rollNumber: 'KOTA-JEE-27-01',
    guardianName: 'Vikram Mehra',
    guardianPhone: '+919810123400',
    guardianRelationship: 'FATHER',
    dpdpConsentGranted: true,
    status: 'ACTIVE',
  },
  {
    id: 'stu-000185',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    studentUniqueId: 'STU-KOTA-2026-002',
    fullName: 'Aarav Singhal',
    gender: 'MALE',
    dob: '2008-11-20',
    phone: '+919414022222',
    batchId: 'bat-jee-2027-evening',
    rollNumber: 'KOTA-JEE-27-02',
    guardianName: 'Sanjay Singhal',
    guardianPhone: '+919810123401',
    guardianRelationship: 'FATHER',
    dpdpConsentGranted: true,
    status: 'ACTIVE',
  },
  {
    id: 'stu-000186',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    studentUniqueId: 'STU-KOTA-2026-003',
    fullName: 'Devansh Tiwari',
    gender: 'MALE',
    dob: '2009-01-08',
    phone: '+919414033333',
    batchId: 'bat-jee-2027-evening',
    rollNumber: 'KOTA-JEE-27-03',
    guardianName: 'Manoj Tiwari',
    guardianPhone: '+919810123402',
    guardianRelationship: 'FATHER',
    dpdpConsentGranted: true,
    status: 'ACTIVE',
  },
  {
    id: 'stu-000187',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    studentUniqueId: 'STU-KOTA-2026-004',
    fullName: 'Priya Sharma',
    gender: 'FEMALE',
    dob: '2008-09-12',
    phone: '+919414044444',
    batchId: 'bat-jee-2027-evening',
    rollNumber: 'KOTA-JEE-27-04',
    guardianName: 'Anita Sharma',
    guardianPhone: '+919810123403',
    guardianRelationship: 'MOTHER',
    dpdpConsentGranted: true,
    status: 'ACTIVE',
  },
  {
    id: 'stu-000188',
    organizationId: 'org-kota-001',
    primaryBranchId: 'br-kota-main',
    studentUniqueId: 'STU-KOTA-2026-005',
    fullName: 'Kabir Verma',
    gender: 'MALE',
    dob: '2009-03-25',
    phone: '+919414055555',
    batchId: 'bat-jee-2027-evening',
    rollNumber: 'KOTA-JEE-27-05',
    guardianName: 'Rohit Verma',
    guardianPhone: '+919810123404',
    guardianRelationship: 'FATHER',
    dpdpConsentGranted: true,
    status: 'ACTIVE',
  }
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead-101',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    source: 'META_ADS',
    studentName: 'Ayush Goel',
    phone: '+919876543210',
    email: 'ayush.goel@gmail.com',
    guardianName: 'Rajeev Goel',
    guardianPhone: '+919876543211',
    interestedCourseId: 'crs-jee-adv',
    assignedCounsellorId: 'usr-pooja-counsellor',
    stage: 'DEMO_SCHEDULED',
    notes: 'Father requested scholarship test details; student scored 94% in Class 10 CBSE boards.',
    followUpDate: '2026-09-22T11:00:00+05:30',
    createdAt: '2026-09-18T14:30:00Z',
  },
  {
    id: 'lead-102',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    source: 'WALK_IN',
    studentName: 'Ananya Deshmukh',
    phone: '+919876543220',
    guardianName: 'Vikas Deshmukh',
    guardianPhone: '+919876543221',
    interestedCourseId: 'crs-jee-adv',
    assignedCounsellorId: 'usr-pooja-counsellor',
    stage: 'NEW',
    notes: 'Visited Talwandi reception. Inquired about hostel facility tie-ups and evening batch timings.',
    followUpDate: '2026-09-21T17:00:00+05:30',
    createdAt: '2026-09-21T10:15:00Z',
  },
  {
    id: 'lead-103',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    source: 'WHATSAPP',
    studentName: 'Tanmay Saxena',
    phone: '+919876543230',
    interestedCourseId: 'crs-jee-adv',
    assignedCounsellorId: 'usr-pooja-counsellor',
    stage: 'CONTACTED',
    notes: 'Inbound message on WhatsApp official number. Shared fee structure and sample study material PDF.',
    followUpDate: '2026-09-23T15:00:00+05:30',
    createdAt: '2026-09-20T09:00:00Z',
  },
];

export const SEED_CLASS_SESSIONS: ClassSession[] = [
  {
    id: 'sess-today-01',
    organizationId: 'org-kota-001',
    batchId: 'bat-jee-2027-evening',
    subjectId: 'sub-phy',
    teacherUserId: 'usr-alok-teacher',
    classroomName: 'Hall 3A (Talwandi)',
    scheduledStart: '2026-09-21T16:00:00+05:30',
    scheduledEnd: '2026-09-21T18:00:00+05:30',
    topicName: 'Newton\'s Third Law & Friction Dynamics',
    status: 'SCHEDULED',
  },
  {
    id: 'sess-prev-01',
    organizationId: 'org-kota-001',
    batchId: 'bat-jee-2027-evening',
    subjectId: 'sub-phy',
    teacherUserId: 'usr-alok-teacher',
    classroomName: 'Hall 3A (Talwandi)',
    scheduledStart: '2026-09-19T16:00:00+05:30',
    scheduledEnd: '2026-09-19T18:00:00+05:30',
    topicName: 'Free Body Diagrams & Pseudo Forces',
    status: 'COMPLETED',
  }
];

export const SEED_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-001',
    organizationId: 'org-kota-001',
    sessionId: 'sess-prev-01',
    studentId: 'stu-000184',
    status: 'PRESENT',
    markedAt: '2026-09-19T16:05:00+05:30',
  },
  {
    id: 'att-002',
    organizationId: 'org-kota-001',
    sessionId: 'sess-prev-01',
    studentId: 'stu-000185',
    status: 'PRESENT',
    markedAt: '2026-09-19T16:05:00+05:30',
  },
  {
    id: 'att-003',
    organizationId: 'org-kota-001',
    sessionId: 'sess-prev-01',
    studentId: 'stu-000186',
    status: 'ABSENT',
    reason: 'Unwell (Informed via parent SMS)',
    markedAt: '2026-09-19T16:05:00+05:30',
  },
  {
    id: 'att-004',
    organizationId: 'org-kota-001',
    sessionId: 'sess-prev-01',
    studentId: 'stu-000187',
    status: 'PRESENT',
    markedAt: '2026-09-19T16:05:00+05:30',
  },
  {
    id: 'att-005',
    organizationId: 'org-kota-001',
    sessionId: 'sess-prev-01',
    studentId: 'stu-000188',
    status: 'LATE',
    reason: 'Hostel bus breakdown',
    markedAt: '2026-09-19T16:25:00+05:30',
  }
];

export const SEED_INVOICES: Invoice[] = [
  {
    id: 'inv-2026-00418',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    studentId: 'stu-000184',
    invoiceNumber: 'INV-2026-AAR-00418',
    totalAmountPaise: 15000000, // Rs 1,50,000.00
    discountAmountPaise: 1500000, // Rs 15,000.00 (Merit Scholarship)
    netAmountPaise: 13500000, // Rs 1,35,000.00
    paidAmountPaise: 5000000, // Rs 50,000.00 paid
    balanceAmountPaise: 8500000, // Rs 85,000.00 remaining
    dueDate: '2026-09-25',
    status: 'PARTIALLY_PAID',
  },
  {
    id: 'inv-2026-00419',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    studentId: 'stu-000185',
    invoiceNumber: 'INV-2026-AAR-00419',
    totalAmountPaise: 15000000,
    discountAmountPaise: 0,
    netAmountPaise: 15000000,
    paidAmountPaise: 15000000,
    balanceAmountPaise: 0,
    dueDate: '2026-06-30',
    status: 'PAID',
  },
  {
    id: 'inv-2026-00420',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    studentId: 'stu-000186',
    invoiceNumber: 'INV-2026-AAR-00420',
    totalAmountPaise: 15000000,
    discountAmountPaise: 2000000,
    netAmountPaise: 13000000,
    paidAmountPaise: 4000000,
    balanceAmountPaise: 9000000,
    dueDate: '2026-09-10', // Overdue!
    status: 'OVERDUE',
  },
];

export const SEED_PAYMENTS: Payment[] = [
  {
    id: 'pay-001',
    organizationId: 'org-kota-001',
    branchId: 'br-kota-main',
    invoiceId: 'inv-2026-00418',
    studentId: 'stu-000184',
    amountPaise: 5000000,
    paymentMethod: 'UPI',
    paymentChannel: 'GATEWAY_LINK',
    provider: 'RAZORPAY',
    providerPaymentId: 'pay_KOTA_9Z12345ABC',
    receiptNumber: 'REC-AAR-2026-00418-1',
    status: 'CAPTURED',
    reconciled: true,
    createdAt: '2026-06-15T12:30:00Z',
  }
];

export const SEED_INTERVENTIONS: Intervention[] = [
  {
    id: 'int-00073',
    organizationId: 'org-kota-001',
    studentId: 'stu-000186',
    studentName: 'Devansh Tiwari',
    batchName: 'JEE Main 2027 Evening',
    triggerReason: 'attendance_and_topic_signal',
    evidenceSummary: 'Missed 2 consecutive classes on Newton Laws; scored 22% in pop quiz; fee instalment overdue by 11 days.',
    status: 'OPEN',
    ownerUserId: 'usr-alok-teacher',
    dueDate: '2026-09-24',
    playbook: '1-on-1 Concept Remedial + Parent Conference Call',
    createdAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'int-00074',
    organizationId: 'org-kota-001',
    studentId: 'stu-000188',
    studentName: 'Kabir Verma',
    batchName: 'JEE Main 2027 Evening',
    triggerReason: 'topic_mastery_decay',
    evidenceSummary: 'Scored below 40th percentile in Vectors and Kinematics test across 3 attempts.',
    status: 'IN_PROGRESS',
    ownerUserId: 'usr-alok-teacher',
    dueDate: '2026-09-26',
    playbook: 'Curated Practice Drill (30 Level-1 Problems) + Teacher Review',
    createdAt: '2026-09-18T10:00:00Z',
  }
];

export const SEED_QUESTIONS: Question[] = [
  {
    id: 'q-phy-001',
    organizationId: 'org-kota-001',
    topicName: 'Newton Laws & Friction',
    questionType: 'SINGLE_CHOICE',
    stemLatex: 'A block of mass $m = 5\\text{ kg}$ rests on a rough horizontal surface with coefficient of static friction $\\mu_s = 0.4$. If a horizontal force $F = 15\\text{ N}$ is applied, what is the magnitude of the frictional force acting on the block? (Take $g = 10\\text{ m/s}^2$)',
    optionsJson: [
      '20 N',
      '15 N',
      '0 N',
      '5 N'
    ],
    correctAnswer: '15 N',
    explanationLatex: 'Maximum limiting static friction is $f_{\\text{max}} = \\mu_s m g = 0.4 \\times 5 \\times 10 = 20\\text{ N}$. Since the applied force $F = 15\\text{ N} < f_{\\text{max}}$, the block does not slip and static friction self-adjusts to equal the applied force: $f = 15\\text{ N}$.',
    difficulty: 'EASY',
    isAiGenerated: false,
  },
  {
    id: 'q-phy-002',
    organizationId: 'org-kota-001',
    topicName: 'Rotational Dynamics',
    questionType: 'SINGLE_CHOICE',
    stemLatex: 'A uniform solid cylinder of mass $M$ and radius $R$ rolls down an inclined plane of inclination $\\theta$ without slipping. The linear acceleration of the center of mass is:',
    optionsJson: [
      '$\\frac{1}{2} g \\sin\\theta$',
      '$\\frac{2}{3} g \\sin\\theta$',
      '$\\frac{3}{4} g \\sin\\theta$',
      '$g \\sin\\theta$'
    ],
    correctAnswer: '$\\frac{2}{3} g \\sin\\theta$',
    explanationLatex: 'For pure rolling down an incline, $a = \\frac{g \\sin\\theta}{1 + \\frac{I}{MR^2}}$. For a solid cylinder, $I = \\frac{1}{2}MR^2$. Thus, $a = \\frac{g \\sin\\theta}{1 + 1/2} = \\frac{2}{3} g \\sin\\theta$.',
    difficulty: 'MEDIUM',
    isAiGenerated: true,
  }
];

export const SEED_TESTS: Test[] = [
  {
    id: 'tst-jee-weekly-04',
    organizationId: 'org-kota-001',
    courseId: 'crs-jee-adv',
    title: 'Weekly Test 04: Newton Laws, Friction & Work Energy',
    totalMarks: 120,
    durationMinutes: 60,
    questionsCount: 30,
    status: 'PUBLISHED',
  }
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    organizationId: 'org-kota-001',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'OWNER',
    action: 'INITIALIZE_ORGANIZATION',
    entityName: 'organizations',
    entityId: 'org-kota-001',
    timestamp: '2026-09-15T09:00:00Z',
  },
  {
    id: 'aud-002',
    organizationId: 'org-kota-001',
    actorName: 'Suresh Nair',
    actorRole: 'ACCOUNTANT',
    action: 'RECORD_PAYMENT',
    entityName: 'payments',
    entityId: 'pay-001',
    timestamp: '2026-06-15T12:30:00Z',
  }
];
